version: '3.8'

services:
  admin-backend:
    build:
      context: .
      dockerfile: ./packages/admin-backend/Dockerfile
      target: production
      cache_from:
        - benalsam/admin-backend:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3002
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com
    ports:
      - "3002:3002"
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  admin-ui:
    build:
      context: .
      dockerfile: ./packages/admin-ui/Dockerfile
      target: production
      cache_from:
        - benalsam/admin-ui:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3003
      - VITE_API_URL=https://admin.benalsam.com/api/v1
      - VITE_ELASTICSEARCH_URL=https://benalsam.com:9200
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com
    ports:
      - "3003:3003"
    depends_on:
      admin-backend:
        condition: service_healthy
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
      target: production
      cache_from:
        - benalsam/web:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=5173
      - VITE_API_URL=https://admin.benalsam.com/api/v1
      - VITE_ELASTICSEARCH_URL=https://benalsam.com:9200
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com
    ports:
      - "5173:5173"
    depends_on:
      admin-backend:
        condition: service_healthy
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.4
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.5
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.6
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.7
    depends_on:
      - admin-backend
      - admin-ui
      - web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'

networks:
  benalsam-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local 