version: '3.8'

services:
  # Admin Backend with hot reload
  admin-backend:
    build:
      context: .
      dockerfile: packages/admin-backend/Dockerfile
    container_name: benalsam-admin-backend-dev
    ports:
      - "3002:3002"
    volumes:
      # Hot reload için source code'u mount et
      - ./packages/admin-backend/src:/app/packages/admin-backend/src
      - ./packages/admin-backend/package.json:/app/packages/admin-backend/package.json
      - ./packages/admin-backend/tsconfig.json:/app/packages/admin-backend/tsconfig.json
      - ./packages/admin-backend/nodemon.json:/app/packages/admin-backend/nodemon.json
      # Shared-types'ı da mount et
      - ./packages/shared-types/src:/app/packages/shared-types/src
      - ./packages/shared-types/package.json:/app/packages/shared-types/package.json
      - ./packages/shared-types/tsconfig.json:/app/packages/shared-types/tsconfig.json
      # Node modules'ı container içinde tut (performance için)
      - /app/node_modules
      - /app/packages/admin-backend/node_modules
      - /app/packages/shared-types/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
      - CORS_ORIGIN=http://localhost:3003,http://localhost:3000,http://localhost:3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./packages/admin-backend/.env
    depends_on:
      - redis
    networks:
      - benalsam-network
    restart: unless-stopped

  # Admin UI with hot reload
  admin-ui:
    build:
      context: ./packages/admin-ui
      dockerfile: Dockerfile
    container_name: benalsam-admin-ui-dev
    ports:
      - "3003:3003"
    volumes:
      # Hot reload için source code'u mount et
      - ./packages/admin-ui/src:/app/src
      - ./packages/admin-ui/package.json:/app/package.json
      - ./packages/admin-ui/vite.config.ts:/app/vite.config.ts
      - ./packages/admin-ui/tsconfig.json:/app/tsconfig.json
      - ./packages/admin-ui/index.html:/app/index.html
      # Node modules'ı container içinde tut (performance için)
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3002/api/v1
    depends_on:
      - admin-backend
    networks:
      - benalsam-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: benalsam-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - benalsam-network
    restart: unless-stopped

  # Elasticsearch (optional for development)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: benalsam-elasticsearch-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - benalsam-network
    restart: unless-stopped

volumes:
  redis_data:
  elasticsearch_data:

networks:
  benalsam-network:
    driver: bridge 