version: '3.8'

services:
  admin-backend:
    build:
      context: .
      dockerfile: ./packages/admin-backend/Dockerfile.clean
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3002
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com
      - NODE_OPTIONS=--max-old-space-size=512
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    ports:
      - "3002:3002"
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'

  admin-ui:
    build:
      context: .
      dockerfile: ./packages/admin-ui/Dockerfile.clean
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3003
      - VITE_API_URL=https://admin.benalsam.com/api/v1
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com
    ports:
      - "3003:3003"
    depends_on:
      admin-backend:
        condition: service_healthy
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile.clean
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5173
      - VITE_API_URL=https://admin.benalsam.com/api/v1
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com
    ports:
      - "5173:5173"
    depends_on:
      admin-backend:
        condition: service_healthy
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.4
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.5
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.15'

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.6
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.minimal.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.7
    depends_on:
      - admin-backend
      - admin-ui
      - web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.05'
        reservations:
          memory: 32M
          cpus: '0.02'

networks:
  benalsam-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local 