version: '3.8'

networks:
  benalsam-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.2

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.3

  admin-backend:
    build:
      context: .
      dockerfile: ./packages/admin-backend/Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=benalsam_listings
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com,http://209.227.228.96:3003,http://209.227.228.96:5173
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - elasticsearch
    command: ["pnpm", "run", "dev"]
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.4

  admin-ui:
    build:
      context: .
      dockerfile: ./packages/admin-ui/Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3003
      - VITE_API_URL=https://benalsam.com/api/v1
      - VITE_ELASTICSEARCH_URL=http://209.227.228.96:9200
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com,http://209.227.228.96:3003,http://209.227.228.96:5173
    ports:
      - "3003:3003"
    depends_on:
      - admin-backend
    command: ["pnpm", "run", "dev"]
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.5

  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=5173
      - VITE_API_URL=https://benalsam.com/api/v1
      - VITE_ELASTICSEARCH_URL=http://209.227.228.96:9200
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CORS_ORIGIN=https://admin.benalsam.com,https://benalsam.com,http://209.227.228.96:3003,http://209.227.228.96:5173
    ports:
      - "5173:5173"
    depends_on:
      - admin-backend
    command: ["pnpm", "run", "dev"]
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.6 