version: '3.8'

networks:
  benalsam-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  redis_data:
  elasticsearch_data:
  postgres_data:

services:
  redis:
    image: redis:7-alpine
    container_name: benalsam-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: benalsam-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.3
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: benalsam-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: benalsam
      POSTGRES_USER: benalsam_user
      POSTGRES_PASSWORD: secure_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      benalsam-network:
        ipv4_address: 172.18.0.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benalsam_user -d benalsam"]
      interval: 30s
      timeout: 10s
      retries: 3 