version: '3.8'

services:
  # Admin Backend (Production)
  admin-backend:
    build:
      context: ./packages/admin-backend
      dockerfile: Dockerfile.prod
    container_name: benalsam-admin-backend-prod
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    env_file:
      - ./packages/admin-backend/.env.production
    depends_on:
      - redis
    networks:
      - benalsam-network
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: benalsam-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - benalsam-network
    restart: unless-stopped
    # Redis configuration for production
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: benalsam-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - admin-backend
    networks:
      - benalsam-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  benalsam-network:
    driver: bridge 