version: '3.8'

services:
  admin-ui:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: benalsam-admin-ui-prod
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - benalsam-network
    depends_on:
      - admin-backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx

  admin-backend:
    build:
      context: ../admin-backend
      dockerfile: Dockerfile.prod
    container_name: benalsam-admin-backend-prod
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - benalsam-network
    environment:
      - NODE_ENV=production
    env_file:
      - ../admin-backend/.env.production
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: benalsam-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - benalsam-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  benalsam-network:
    driver: bridge

volumes:
  redis_data: 