name: Web Admin Backend Integration - CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'packages/web/**'
      - 'packages/shared-types/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'packages/web/**'
      - 'packages/shared-types/**'

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          cd packages/web
          npm ci
          
      - name: Run tests
        run: |
          cd packages/web
          npm run test:run
          
      - name: Run type check
        run: |
          cd packages/web
          npm run type-check

  build:
    name: Build & Analyze
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          cd packages/web
          npm ci
          
      - name: Build production
        run: |
          cd packages/web
          npm run build:prod
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: packages/web/dist
          retention-days: 7

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          cd packages/web
          npm ci
          
      - name: Run security audit
        run: |
          cd packages/web
          npm audit --audit-level=moderate

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [test, build, security-audit]
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: packages/web/dist
          
      - name: Deploy to staging server
        run: |
          echo "Deploying to staging server..."
          # Add your staging deployment commands here
          # Example: rsync, scp, or cloud deployment

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, build, security-audit]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: packages/web/dist
          
      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          # Add your production deployment commands here
          # Example: rsync, scp, or cloud deployment 